var products = []
products.largeImage = {converted: 400, price: 400, class: '.priceSize', text: 'Large painting'};
products.mediumImage = {converted: 200,price: 200, class: '.priceSize', text: 'Medium painting'};
products.smallImage = {converted: 100, price: 100, class: '.priceSize', text: 'Small painting'};
products.video = {converted: 200, price: 200, class: '.videoPrice', text: 'Video message'};
products.frameMount = {converted: 400, price: 400, class: '.frameMount', text: 'Mounted frame'};
products.frameWithoutMount = {converted: 0, price: 300, class: '.frameWithoutMount', text: 'Normal frame'};
products.giftWrap = {converted: 100, price: 100, class: '.giftWrap', text: 'Gift wrap'};
products.message = {converted: 150, price: 150, class: '.messageChild', text: 'Message from artist'};
